# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-datalab
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  title: Google Datalab Terraform Module
  source:
    repo: https://github.com/terraform-google-modules/terraform-google-datalab.git
    sourceType: git
  subBlueprints:
  - name: iap_firewall
    location: modules/iap_firewall
  - name: instance
    location: modules/instance
  - name: template_files
    location: modules/template_files
  examples:
  - name: advance
    location: examples/advance
  - name: basic
    location: examples/basic
  roles:
  - level: Project
    roles:
    - roles/compute.admin
    - roles/iam.serviceAccountUser
    - roles/iam.serviceAccountAdmin
    - roles/resourcemanager.projectIamAdmin
  services:
  - cloudresourcemanager.googleapis.com
  - storage-api.googleapis.com
  - serviceusage.googleapis.com
  - compute.googleapis.com
  - iap.googleapis.com
  - iam.googleapis.com
  - iamcredentials.googleapis.com
