# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-datalab
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  title: Google Cloud Private Datalab‎ IAP Firewall
  source:
    repo: https://github.com/terraform-google-modules/terraform-google-datalab.git
    sourceType: git
  actuationTool:
    type: Terraform
    version: '>= 0.13'
  examples:
  - name: advance
    location: examples/advance
  - name: basic
    location: examples/basic
  variables:
  - name: create_rule
    description: Flag to create or skip Firewall rule creation
    type: bool
    default: true
    required: false
  - name: firewall_description
    description: Description for firewall rule
    type: string
    default: Allow IAP access
    required: false
  - name: network_name
    description: The network the Datalab instance will be in
    type: string
    required: true
  - name: ports
    description: A list of ports to which this rule applies
    type: list(any)
    required: true
  - name: project_id
    description: The project ID used for the Datalab instance
    type: string
    required: true
  - name: target_tags
    description: A list of instance tags indicating sets of instances located in the network that may make network connections as specified
    type: list(any)
    required: true
  outputs:
  - name: firewall_name
    description: The name of the firewall rule
  roles:
  - level: Project
    roles:
    - roles/compute.admin
    - roles/iam.serviceAccountUser
    - roles/iam.serviceAccountAdmin
    - roles/resourcemanager.projectIamAdmin
  services:
  - cloudresourcemanager.googleapis.com
  - storage-api.googleapis.com
  - serviceusage.googleapis.com
  - compute.googleapis.com
  - iap.googleapis.com
  - iam.googleapis.com
  - iamcredentials.googleapis.com
